---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    'ohai.plugin_path <<': '/tmp/kitchen/ohai/plugins'

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  #- name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[ohai_scsi::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
